version: 0.2

env:
  parameter-store:
    AWS_ACCOUNT_ID: /$ENV_NAME/codebuild/AWS_ACCOUNT_ID

phases:
  pre_build:
    on-failure: ABORT
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo IMAGE_TAG $IMAGE_TAG
  build:
    on-failure: ABORT
    commands:
      - echo build node image
      - docker build -build-arg NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL -t $ECR_NAME:$IMAGE_TAG -f ./Dockerfile . # イメージの作成とタグ付け
      - docker tag $ECR_NAME:$IMAGE_TAG $ECR_REPOSITORY_URL:$IMAGE_TAG
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REPOSITORY_URL:$IMAGE_TAG
      - cp ./aws/imagedefinitions.json .
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $ECR_REPOSITORY_URL:$IMAGE_TAG > imagedefinitions.json
      - echo "$(cat imagedefinitions.json)"
      # パラメータストアを更新
      - echo "Updating SSM parameter with image URI..."
      - echo "ENV_NAME=$ENV_NAME"
      - echo "ECR_REPOSITORY_URL=$ECR_REPOSITORY_URL"
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - aws ssm put-parameter --name "/$ENV_NAME/ecs/WEB_STAFF_IMAGE_URI" --value "$ECR_REPOSITORY_URL:$IMAGE_TAG" --type String --overwrite
      # 1. 最新のタスク定義の ARN を取得
      # ECS から指定したファミリーの最新リビジョンの ARN を取得
      - echo "Fetching task definition ARN from SSM Parameter Store..."
      - TASK_DEF_ARN=$(aws ssm get-parameter --name "/$ENV_NAME/ecs/WEB_STAFF_TASK_DEF_ARN" --query "Parameter.Value" --output text)
      # 2. タスク定義の JSON を取得
      # タスク定義全体を JSON として出力し、ファイルに保存
      - aws ecs describe-task-definition --task-definition $TASK_DEF_ARN --query "taskDefinition" > task-def-latest.json
      # 3. 再登録できないフィールドを削除
      # status, revision, taskDefinitionArn など、再登録不可な項目を jq で削除
      - cat task-def-latest.json | jq 'del(.status, .revision, .taskDefinitionArn, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' > task-def-editable.json
      # 4. イメージ URI を更新
      # containerDefinitions[0].image に新しい ECR イメージ URI を上書き
      - jq --arg IMAGE "$ECR_REPOSITORY_URL:$IMAGE_TAG" '.containerDefinitions[0].image = $IMAGE' task-def-editable.json > task-def-new.json
      # 5. 新しいタスク定義を登録
      # 編集した JSON を元に ECS にタスク定義を登録
      - |
        echo "Registering new task definition and storing ARN to SSM..."
        NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://task-def-new.json --query "taskDefinition.taskDefinitionArn" --output text)
        echo "New Task Definition ARN: $NEW_TASK_DEF_ARN"
        aws ssm put-parameter --name "/$ENV_NAME/ecs/WEB_STAFF_TASK_DEF_ARN" --value "$NEW_TASK_DEF_ARN" --type String --overwrite

artifacts:
  files:
    - imagedefinitions.json